// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-07 21:40:58.21024 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Byte is an optional byte.
type Byte struct {
	val byte
	set bool
}

// MakeByte creates an optional.Byte from a byte.
func MakeByte(v byte) Byte {
	return Byte{val: v, set: true}
}

// Set sets the byte value.
func (b *Byte) Set(v byte) {
	*b = Byte{val: v, set: true}
}

// Unset unsets the byte value.
func (b *Byte) Unset() {
	*b = Byte{}
}

// Get returns the byte value or an error if not present.
func (b Byte) Get() (byte, error) {
	if !b.Present() {
		var zero byte
		return zero, errors.New("value not present")
	}
	return b.val, nil
}

// Present returns whether or not the value is present.
func (b Byte) Present() bool {
	return b.set
}

// OrElse returns the byte value or a default value if the value is not present.
func (b Byte) OrElse(v byte) byte {
	if b.Present() {
		return b.val
	}
	return v
}

// If calls the function f with the value if the value is present.
func (b Byte) If(fn func(byte)) {
	if b.Present() {
		fn(b.val)
	}
}

// MarshalJSON implements the json.Marshaler interface.
func (b Byte) MarshalJSON() ([]byte, error) {
	if b.Present() {
		return json.Marshal(b.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (b *Byte) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		b.Unset()
		return nil
	}

	var value byte
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	b.Set(value)
	return nil
}
