// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-07 21:49:10.687383 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Complex128 is an optional complex128.
type Complex128 struct {
	val complex128
	set bool
}

// MakeComplex128 creates an optional.Complex128 from a complex128.
func MakeComplex128(v complex128) Complex128 {
	return Complex128{val: v, set: true}
}

// Set sets the complex128 value.
func (c *Complex128) Set(v complex128) {
	*c = Complex128{val: v, set: true}
}

// Unset unsets the complex128 value.
func (c *Complex128) Unset() {
	*c = Complex128{}
}

// Present returns whether or not the value is present.
func (c Complex128) Present() bool {
	return c.set
}

// Get returns the complex128 value or an error if not present.
func (c Complex128) Get() (complex128, error) {
	if !c.Present() {
		var zero complex128
		return zero, errors.New("value not present")
	}
	return c.val, nil
}

// MustGet returns the complex128 value or panics if not present.
func (c Complex128) MustGet() complex128 {
	if !c.Present() {
		panic("value not present")
	}
	return c.val
}

// OrElse returns the complex128 value or a default value if the value is not present.
func (c Complex128) OrElse(v complex128) complex128 {
	if c.Present() {
		return c.val
	}
	return v
}

// If calls the function f with the value if the value is present.
func (c Complex128) If(fn func(complex128)) {
	if c.Present() {
		fn(c.val)
	}
}

// MarshalJSON implements the json.Marshaler interface.
func (c Complex128) MarshalJSON() ([]byte, error) {
	if c.Present() {
		return json.Marshal(c.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (c *Complex128) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		c.Unset()
		return nil
	}

	var value complex128
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	c.Set(value)
	return nil
}
