// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-10 22:06:19.85529 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Int16 is an optional int16.
type Int16 struct {
	val int16
	set bool
}

// MakeInt16 creates an optional.Int16 from a int16.
func MakeInt16(v int16) Int16 {
	return Int16{val: v, set: true}
}

// Set sets the int16 value.
func (i *Int16) Set(v int16) {
	*i = MakeInt16(v)
}

// Unset unsets the int16 value.
func (i *Int16) Unset() {
	*i = Int16{}
}

// Present returns whether or not the value is present.
func (i Int16) Present() bool {
	return i.set
}

// Get returns the int16 value or panics if not present.
func (i Int16) Get() int16 {
	if !i.Present() {
		panic("value not present")
	}
	return i.val
}

// GetOr returns the int16 value or a default value if not present.
func (i Int16) GetOr(v int16) int16 {
	if i.Present() {
		return i.val
	}
	return v
}

// GetOrBool returns the int16 value or false if not present.
func (i Int16) GetOrBool() (int16, bool) {
	if !i.Present() {
		var zero int16
		return zero, false
	}
	return i.val, true
}

// GetOrErr returns the int16 value or an error if not present.
func (i Int16) GetOrErr() (int16, error) {
	if !i.Present() {
		var zero int16
		return zero, errors.New("value not present")
	}
	return i.val, nil
}

// If calls the function fn with the value if the value is present.
func (i Int16) If(fn func(int16)) {
	if i.Present() {
		fn(i.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (i Int16) Map(fn func(int16) int16) Int16 {
	if i.Present() {
		return MakeInt16(fn(i.val))
	}
	return i
}

// And returns an empty Int16 option value if not present, otherwise returns
// optb.
func (i Int16) And(optb Int16) Int16 {
	if i.Present() {
		return optb
	}
	return Int16{}
}

// Or returns the Int16 option value if present, otherwise returns optb.
func (i Int16) Or(optb Int16) Int16 {
	if i.Present() {
		return i
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (i Int16) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (i *Int16) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		i.Unset()
		return nil
	}

	var value int16
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	i.Set(value)
	return nil
}
