// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-10 22:06:20.68106 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Int64 is an optional int64.
type Int64 struct {
	val int64
	set bool
}

// MakeInt64 creates an optional.Int64 from a int64.
func MakeInt64(v int64) Int64 {
	return Int64{val: v, set: true}
}

// Set sets the int64 value.
func (i *Int64) Set(v int64) {
	*i = MakeInt64(v)
}

// Unset unsets the int64 value.
func (i *Int64) Unset() {
	*i = Int64{}
}

// Present returns whether or not the value is present.
func (i Int64) Present() bool {
	return i.set
}

// Get returns the int64 value or panics if not present.
func (i Int64) Get() int64 {
	if !i.Present() {
		panic("value not present")
	}
	return i.val
}

// GetOr returns the int64 value or a default value if not present.
func (i Int64) GetOr(v int64) int64 {
	if i.Present() {
		return i.val
	}
	return v
}

// GetOrBool returns the int64 value or false if not present.
func (i Int64) GetOrBool() (int64, bool) {
	if !i.Present() {
		var zero int64
		return zero, false
	}
	return i.val, true
}

// GetOrErr returns the int64 value or an error if not present.
func (i Int64) GetOrErr() (int64, error) {
	if !i.Present() {
		var zero int64
		return zero, errors.New("value not present")
	}
	return i.val, nil
}

// If calls the function fn with the value if the value is present.
func (i Int64) If(fn func(int64)) {
	if i.Present() {
		fn(i.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (i Int64) Map(fn func(int64) int64) Int64 {
	if i.Present() {
		return MakeInt64(fn(i.val))
	}
	return i
}

// And returns an empty Int64 option value if not present, otherwise returns
// optb.
func (i Int64) And(optb Int64) Int64 {
	if i.Present() {
		return optb
	}
	return Int64{}
}

// Or returns the Int64 option value if present, otherwise returns optb.
func (i Int64) Or(optb Int64) Int64 {
	if i.Present() {
		return i
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (i Int64) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (i *Int64) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		i.Unset()
		return nil
	}

	var value int64
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	i.Set(value)
	return nil
}
