// Code generated by go generate
// This file was generated by robots at 2020-04-07 21:38:39.920666 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Int8 is an optional int8.
type Int8 struct {
	val int8
	set bool
}

// MakeInt8 creates an optional.Int8 from a int8.
func MakeInt8(v int8) Int8 {
	return Int8{val: v, set: true}
}

// Set sets the int8 value.
func (i *Int8) Set(v int8) {
	*i = Int8{val: v, set: true}
}

// Unset unsets the int8 value.
func (i *Int8) Unset() {
	*i = Int8{}
}

// Get returns the int8 value or an error if not present.
func (i Int8) Get() (int8, error) {
	if !i.Present() {
		var zero int8
		return zero, errors.New("value not present")
	}
	return i.val, nil
}

// Present returns whether or not the value is present.
func (i Int8) Present() bool {
	return i.set
}

// OrElse returns the int8 value or a default value if the value is not present.
func (i Int8) OrElse(v int8) int8 {
	if i.Present() {
		return i.val
	}
	return v
}

// If calls the function f with the value if the value is present.
func (i Int8) If(fn func(int8)) {
	if i.Present() {
		fn(i.val)
	}
}

// MarshalJSON implements the json.Marshaler interface.
func (i Int8) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (i *Int8) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		i.Unset()
		return nil
	}

	var value int8
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	i.Set(value)
	return nil
}
