// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-08 04:05:19.016708 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Uint16 is an optional uint16.
type Uint16 struct {
	val uint16
	set bool
}

// MakeUint16 creates an optional.Uint16 from a uint16.
func MakeUint16(v uint16) Uint16 {
	return Uint16{val: v, set: true}
}

// Set sets the uint16 value.
func (u *Uint16) Set(v uint16) {
	*u = Uint16{val: v, set: true}
}

// Unset unsets the uint16 value.
func (u *Uint16) Unset() {
	*u = Uint16{}
}

// Present returns whether or not the value is present.
func (u Uint16) Present() bool {
	return u.set
}

// Get returns the uint16 value or panics if not present.
func (u Uint16) Get() uint16 {
	if !u.Present() {
		panic("value not present")
	}
	return u.val
}

// GetOr returns the uint16 value or a default value if not present.
func (u Uint16) GetOr(v uint16) uint16 {
	if u.Present() {
		return u.val
	}
	return v
}

// GetOrErr returns the uint16 value or an error if not present.
func (u Uint16) GetOrErr() (uint16, error) {
	if !u.Present() {
		var zero uint16
		return zero, errors.New("value not present")
	}
	return u.val, nil
}

// If calls the function fn with the value if the value is present.
func (u Uint16) If(fn func(uint16)) {
	if u.Present() {
		fn(u.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (u Uint16) Map(fn func(uint16) uint16) Uint16 {
	if u.Present() {
		return MakeUint16(fn(u.val))
	}
	return u
}

// And returns an empty Uint16 option value if not present, otherwise returns
// optb.
func (u Uint16) And(optb Uint16) Uint16 {
	if u.Present() {
		return optb
	}
	return Uint16{}
}

// Or returns the Uint16 option value if present, otherwise returns optb.
func (u Uint16) Or(optb Uint16) Uint16 {
	if u.Present() {
		return u
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (u Uint16) MarshalJSON() ([]byte, error) {
	if u.Present() {
		return json.Marshal(u.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (u *Uint16) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		u.Unset()
		return nil
	}

	var value uint16
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	u.Set(value)
	return nil
}
