// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-10 22:06:24.465522 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Uint8 is an optional uint8.
type Uint8 struct {
	val uint8
	set bool
}

// MakeUint8 creates an optional.Uint8 from a uint8.
func MakeUint8(v uint8) Uint8 {
	return Uint8{val: v, set: true}
}

// Set sets the uint8 value.
func (u *Uint8) Set(v uint8) {
	*u = MakeUint8(v)
}

// Unset unsets the uint8 value.
func (u *Uint8) Unset() {
	*u = Uint8{}
}

// Present returns whether or not the value is present.
func (u Uint8) Present() bool {
	return u.set
}

// Get returns the uint8 value or panics if not present.
func (u Uint8) Get() uint8 {
	if !u.Present() {
		panic("value not present")
	}
	return u.val
}

// GetOr returns the uint8 value or a default value if not present.
func (u Uint8) GetOr(v uint8) uint8 {
	if u.Present() {
		return u.val
	}
	return v
}

// GetOrBool returns the uint8 value or false if not present.
func (u Uint8) GetOrBool() (uint8, bool) {
	if !u.Present() {
		var zero uint8
		return zero, false
	}
	return u.val, true
}

// GetOrErr returns the uint8 value or an error if not present.
func (u Uint8) GetOrErr() (uint8, error) {
	if !u.Present() {
		var zero uint8
		return zero, errors.New("value not present")
	}
	return u.val, nil
}

// If calls the function fn with the value if the value is present.
func (u Uint8) If(fn func(uint8)) {
	if u.Present() {
		fn(u.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (u Uint8) Map(fn func(uint8) uint8) Uint8 {
	if u.Present() {
		return MakeUint8(fn(u.val))
	}
	return u
}

// And returns an empty Uint8 option value if not present, otherwise returns
// optb.
func (u Uint8) And(optb Uint8) Uint8 {
	if u.Present() {
		return optb
	}
	return Uint8{}
}

// Or returns the Uint8 option value if present, otherwise returns optb.
func (u Uint8) Or(optb Uint8) Uint8 {
	if u.Present() {
		return u
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (u Uint8) MarshalJSON() ([]byte, error) {
	if u.Present() {
		return json.Marshal(u.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (u *Uint8) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		u.Unset()
		return nil
	}

	var value uint8
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	u.Set(value)
	return nil
}
