// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-10 23:14:23.824132 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

// Uint64 is an optional uint64.
type Uint64 struct {
	val uint64
	set bool
}

// MakeUint64 creates an optional.Uint64 from a uint64.
func MakeUint64(v uint64) Uint64 {
	return Uint64{val: v, set: true}
}

// Set sets the uint64 value.
func (u *Uint64) Set(v uint64) {
	*u = MakeUint64(v)
}

// Unset unsets the uint64 value.
func (u *Uint64) Unset() {
	*u = Uint64{}
}

// Present returns whether or not the value is present.
func (u Uint64) Present() bool {
	return u.set
}

// Get returns the uint64 value or panics if not present.
func (u Uint64) Get() uint64 {
	if !u.Present() {
		panic("value not present")
	}
	return u.val
}

// GetOr returns the uint64 value or a default value if not present.
func (u Uint64) GetOr(v uint64) uint64 {
	if u.Present() {
		return u.val
	}
	return v
}

// GetOrBool returns the uint64 value or false if not present.
func (u Uint64) GetOrBool() (uint64, bool) {
	if !u.Present() {
		var zero uint64
		return zero, false
	}
	return u.val, true
}

// GetOrErr returns the uint64 value or an error if not present.
func (u Uint64) GetOrErr() (uint64, error) {
	if !u.Present() {
		var zero uint64
		return zero, errors.New("value not present")
	}
	return u.val, nil
}

// If calls the function fn with the value if the value is present.
func (u Uint64) If(fn func(uint64)) {
	if u.Present() {
		fn(u.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (u Uint64) Map(fn func(uint64) uint64) Uint64 {
	if u.Present() {
		return MakeUint64(fn(u.val))
	}
	return u
}

// And returns an empty Uint64 option value if not present, otherwise returns
// optb.
func (u Uint64) And(optb Uint64) Uint64 {
	if u.Present() {
		return optb
	}
	return Uint64{}
}

// Or returns the Uint64 option value if present, otherwise returns optb.
func (u Uint64) Or(optb Uint64) Uint64 {
	if u.Present() {
		return u
	}
	return optb
}

// Format implements the fmt.Formatter interface.
func (u Uint64) Format(fmtS fmt.State, verb rune) {
	if !u.Present() {
		io.WriteString(fmtS, "none")
		return
	}
	var format string
	switch verb {
	case 'v':
		if fmtS.Flag('+') {
			format = "some(%+v)"
		} else {
			format = "some(%v)"
		}
	case 's':
		format = "some(%v)"
	case 'q':
		format = "\"some(%v)\""
	}
	fmt.Fprintf(fmtS, format, u.val)
}

// MarshalJSON implements the json.Marshaler interface.
func (u Uint64) MarshalJSON() ([]byte, error) {
	if u.Present() {
		return json.Marshal(u.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (u *Uint64) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		u.Unset()
		return nil
	}

	var value uint64
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	u.Set(value)
	return nil
}
