// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-10 22:06:24.879045 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Uintptr is an optional uintptr.
type Uintptr struct {
	val uintptr
	set bool
}

// MakeUintptr creates an optional.Uintptr from a uintptr.
func MakeUintptr(v uintptr) Uintptr {
	return Uintptr{val: v, set: true}
}

// Set sets the uintptr value.
func (u *Uintptr) Set(v uintptr) {
	*u = MakeUintptr(v)
}

// Unset unsets the uintptr value.
func (u *Uintptr) Unset() {
	*u = Uintptr{}
}

// Present returns whether or not the value is present.
func (u Uintptr) Present() bool {
	return u.set
}

// Get returns the uintptr value or panics if not present.
func (u Uintptr) Get() uintptr {
	if !u.Present() {
		panic("value not present")
	}
	return u.val
}

// GetOr returns the uintptr value or a default value if not present.
func (u Uintptr) GetOr(v uintptr) uintptr {
	if u.Present() {
		return u.val
	}
	return v
}

// GetOrBool returns the uintptr value or false if not present.
func (u Uintptr) GetOrBool() (uintptr, bool) {
	if !u.Present() {
		var zero uintptr
		return zero, false
	}
	return u.val, true
}

// GetOrErr returns the uintptr value or an error if not present.
func (u Uintptr) GetOrErr() (uintptr, error) {
	if !u.Present() {
		var zero uintptr
		return zero, errors.New("value not present")
	}
	return u.val, nil
}

// If calls the function fn with the value if the value is present.
func (u Uintptr) If(fn func(uintptr)) {
	if u.Present() {
		fn(u.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (u Uintptr) Map(fn func(uintptr) uintptr) Uintptr {
	if u.Present() {
		return MakeUintptr(fn(u.val))
	}
	return u
}

// And returns an empty Uintptr option value if not present, otherwise returns
// optb.
func (u Uintptr) And(optb Uintptr) Uintptr {
	if u.Present() {
		return optb
	}
	return Uintptr{}
}

// Or returns the Uintptr option value if present, otherwise returns optb.
func (u Uintptr) Or(optb Uintptr) Uintptr {
	if u.Present() {
		return u
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (u Uintptr) MarshalJSON() ([]byte, error) {
	if u.Present() {
		return json.Marshal(u.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (u *Uintptr) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		u.Unset()
		return nil
	}

	var value uintptr
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	u.Set(value)
	return nil
}
