// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-20 22:48:08.964584 +0000 UTC

package foo

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

// OptionalFooPtr is an optional *Foo.
type OptionalFooPtr struct {
	val *Foo
	set bool
}

// MakeOptionalFooPtr creates an optional.OptionalFooPtr from a *Foo.
func MakeOptionalFooPtr(v *Foo) OptionalFooPtr {
	return OptionalFooPtr{val: v, set: true}
}

// Set sets the *Foo value.
func (o *OptionalFooPtr) Set(v *Foo) {
	*o = MakeOptionalFooPtr(v)
}

// Unset unsets the *Foo value.
func (o *OptionalFooPtr) Unset() {
	*o = OptionalFooPtr{}
}

// Present returns whether or not the value is present.
func (o OptionalFooPtr) Present() bool {
	return o.set
}

// Get returns the *Foo value or panics if not present.
func (o OptionalFooPtr) Get() *Foo {
	if !o.Present() {
		panic("value not present")
	}
	return o.val
}

// GetOr returns the *Foo value or a default value if not present.
func (o OptionalFooPtr) GetOr(v *Foo) *Foo {
	if o.Present() {
		return o.val
	}
	return v
}

// GetOrBool returns the *Foo value or false if not present.
func (o OptionalFooPtr) GetOrBool() (*Foo, bool) {
	if !o.Present() {
		var zero *Foo
		return zero, false
	}
	return o.val, true
}

// GetOrErr returns the *Foo value or an error if not present.
func (o OptionalFooPtr) GetOrErr() (*Foo, error) {
	if !o.Present() {
		var zero *Foo
		return zero, errors.New("value not present")
	}
	return o.val, nil
}

// If calls the function fn with the value if the value is present.
func (o OptionalFooPtr) If(fn func(*Foo)) {
	if o.Present() {
		fn(o.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (o OptionalFooPtr) Map(fn func(*Foo) *Foo) OptionalFooPtr {
	if o.Present() {
		return MakeOptionalFooPtr(fn(o.val))
	}
	return o
}

// And returns an empty OptionalFooPtr option value if not present, otherwise returns
// optb.
func (o OptionalFooPtr) And(optb OptionalFooPtr) OptionalFooPtr {
	if o.Present() {
		return optb
	}
	return OptionalFooPtr{}
}

// Or returns the OptionalFooPtr option value if present, otherwise returns optb.
func (o OptionalFooPtr) Or(optb OptionalFooPtr) OptionalFooPtr {
	if o.Present() {
		return o
	}
	return optb
}

// Format implements the fmt.Formatter interface.
func (o OptionalFooPtr) Format(fmtS fmt.State, verb rune) {
	if !o.Present() {
		io.WriteString(fmtS, "none")
		return
	}
	var format string
	switch verb {
	case 'v':
		if fmtS.Flag('+') {
			format = "some(%+v)"
		} else {
			format = "some(%v)"
		}
	case 's':
		format = "some(%v)"
	case 'q':
		format = "\"some(%v)\""
	}
	fmt.Fprintf(fmtS, format, o.val)
}

// MarshalJSON implements the json.Marshaler interface.
func (o OptionalFooPtr) MarshalJSON() ([]byte, error) {
	if o.Present() {
		return json.Marshal(o.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (o *OptionalFooPtr) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.Unset()
		return nil
	}

	var value *Foo
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	o.Set(value)
	return nil
}
