// Code generated by go generate. DO NOT EDIT.
// This file was generated by robots at 2020-04-08 04:05:00.901368 +0000 UTC

package foo

import (
	"encoding/json"
	"errors"
)

// OptionalFoo is an optional Foo.
type OptionalFoo struct {
	val Foo
	set bool
}

// MakeOptionalFoo creates an optional.OptionalFoo from a Foo.
func MakeOptionalFoo(v Foo) OptionalFoo {
	return OptionalFoo{val: v, set: true}
}

// Set sets the Foo value.
func (o *OptionalFoo) Set(v Foo) {
	*o = OptionalFoo{val: v, set: true}
}

// Unset unsets the Foo value.
func (o *OptionalFoo) Unset() {
	*o = OptionalFoo{}
}

// Present returns whether or not the value is present.
func (o OptionalFoo) Present() bool {
	return o.set
}

// Get returns the Foo value or panics if not present.
func (o OptionalFoo) Get() Foo {
	if !o.Present() {
		panic("value not present")
	}
	return o.val
}

// GetOr returns the Foo value or a default value if not present.
func (o OptionalFoo) GetOr(v Foo) Foo {
	if o.Present() {
		return o.val
	}
	return v
}

// GetOrErr returns the Foo value or an error if not present.
func (o OptionalFoo) GetOrErr() (Foo, error) {
	if !o.Present() {
		var zero Foo
		return zero, errors.New("value not present")
	}
	return o.val, nil
}

// If calls the function fn with the value if the value is present.
func (o OptionalFoo) If(fn func(Foo)) {
	if o.Present() {
		fn(o.val)
	}
}

// Map applies the function fn to the contained value (if any) and returns a new
// option value.
func (o OptionalFoo) Map(fn func(Foo) Foo) OptionalFoo {
	if o.Present() {
		return MakeOptionalFoo(fn(o.val))
	}
	return o
}

// And returns an empty OptionalFoo option value if not present, otherwise returns
// optb.
func (o OptionalFoo) And(optb OptionalFoo) OptionalFoo {
	if o.Present() {
		return optb
	}
	return OptionalFoo{}
}

// Or returns the OptionalFoo option value if present, otherwise returns optb.
func (o OptionalFoo) Or(optb OptionalFoo) OptionalFoo {
	if o.Present() {
		return o
	}
	return optb
}

// MarshalJSON implements the json.Marshaler interface.
func (o OptionalFoo) MarshalJSON() ([]byte, error) {
	if o.Present() {
		return json.Marshal(o.val)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (o *OptionalFoo) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.Unset()
		return nil
	}

	var value Foo
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	o.Set(value)
	return nil
}
